export const SUCCESS_GET_DATA = "SUCCESS_GET_DATA"
export const FAILED_GET_DATA = "FAILED_GET_DATA"

export const SUCCESS_CREATE_DATA = "SUCCESS_CREATE_DATA"
export const FAILED_CREATE_DATA = "FAILED_CREATE_DATA"

export const SUCCESS_DELETE_DATA = "SUCCESS_DELETE_DATA"
export const FAILED_DELETE_DATA = "FAILED_DELETE_DATA"

export const SUCCESS_GET_ID_DETAIL = "SUCCESS_GET_ID_DETAIL"

export const SUCCESS_UPDATE_DATA = "SUCCESS_UPDATE_DATA"
export const FAILED_UPDATE_DATA = "FAILED_UPDATE_DATA"